// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(GenesisBrewContext))]
    partial class GenesisBrewContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.BeerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BreweryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a816ebf-0265-4f20-80fd-cbaf938fad6b"),
                            BreweryId = new Guid("d985e71e-7b84-48af-8b32-fd87148d9c71"),
                            IsObsolete = false,
                            Name = "Willy Blond"
                        },
                        new
                        {
                            Id = new Guid("79a13c8e-cbac-480d-910a-87b809cd8605"),
                            BreweryId = new Guid("25c74345-961b-49ac-9d2f-ed94123b3cc8"),
                            IsObsolete = false,
                            Name = "Genesis IPA"
                        },
                        new
                        {
                            Id = new Guid("dfabc6de-6ca1-4ec0-a10a-d4afe86d8dd3"),
                            BreweryId = new Guid("5fafa7da-1759-424d-a78f-ef81fe6479f8"),
                            IsObsolete = false,
                            Name = "Supreme Red"
                        },
                        new
                        {
                            Id = new Guid("3919b3af-db1d-481b-9f4a-a75b241e46ab"),
                            BreweryId = new Guid("cdb9fe2e-cda2-4c91-9a1b-35da889a9bed"),
                            IsObsolete = false,
                            Name = "Du vin"
                        },
                        new
                        {
                            Id = new Guid("bcfb22cf-e6ee-4ee5-969e-1e1bdae09edf"),
                            BreweryId = new Guid("cdb9fe2e-cda2-4c91-9a1b-35da889a9bed"),
                            IsObsolete = false,
                            Name = "Toujours du vin"
                        },
                        new
                        {
                            Id = new Guid("a30a3e77-4d7e-4ef8-9200-d2609fad5d11"),
                            BreweryId = new Guid("426b9381-8de1-4b49-a600-035a99617984"),
                            IsObsolete = false,
                            Name = "Cara"
                        },
                        new
                        {
                            Id = new Guid("54e4edd5-be1d-43c8-ab7d-c7073077985f"),
                            BreweryId = new Guid("426b9381-8de1-4b49-a600-035a99617984"),
                            IsObsolete = false,
                            Name = "Heineken"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BeerStockItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.Property<Guid>("WholesalerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("WholesalerId");

                    b.ToTable("StockItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d41d3f72-09f6-47e4-a23c-83023748bc6d"),
                            BeerId = new Guid("5a816ebf-0265-4f20-80fd-cbaf938fad6b"),
                            Quantity = 2,
                            UnitPrice = 1.5f,
                            WholesalerId = new Guid("eb891f07-af99-4f36-a2d4-0065cd8a1989")
                        },
                        new
                        {
                            Id = new Guid("9b35f3f2-cd7d-4c7b-ba71-f6d550943075"),
                            BeerId = new Guid("79a13c8e-cbac-480d-910a-87b809cd8605"),
                            Quantity = 3,
                            UnitPrice = 2.5f,
                            WholesalerId = new Guid("7ec52a66-5ce1-41ea-804c-2912873131fe")
                        },
                        new
                        {
                            Id = new Guid("0a9cfaa4-5eb6-4f40-b866-915db026acd5"),
                            BeerId = new Guid("dfabc6de-6ca1-4ec0-a10a-d4afe86d8dd3"),
                            Quantity = 25,
                            UnitPrice = 1.6f,
                            WholesalerId = new Guid("eb891f07-af99-4f36-a2d4-0065cd8a1989")
                        },
                        new
                        {
                            Id = new Guid("6ad2fe99-5e9d-4c65-af04-c64d444621b8"),
                            BeerId = new Guid("3919b3af-db1d-481b-9f4a-a75b241e46ab"),
                            Quantity = 4,
                            UnitPrice = 1.9f,
                            WholesalerId = new Guid("68e33f1d-fefa-40f6-a117-5e601bd8a354")
                        },
                        new
                        {
                            Id = new Guid("5c522eb3-bfb7-4f90-b4de-798cb9f6ce80"),
                            BeerId = new Guid("bcfb22cf-e6ee-4ee5-969e-1e1bdae09edf"),
                            Quantity = 2,
                            UnitPrice = 3.2f,
                            WholesalerId = new Guid("eb891f07-af99-4f36-a2d4-0065cd8a1989")
                        },
                        new
                        {
                            Id = new Guid("51c8674f-4d63-4fba-8e5c-a9c34357bf65"),
                            BeerId = new Guid("a30a3e77-4d7e-4ef8-9200-d2609fad5d11"),
                            Quantity = 6,
                            UnitPrice = 0.5f,
                            WholesalerId = new Guid("68e33f1d-fefa-40f6-a117-5e601bd8a354")
                        },
                        new
                        {
                            Id = new Guid("96494845-60eb-493b-8972-aeda77583136"),
                            BeerId = new Guid("54e4edd5-be1d-43c8-ab7d-c7073077985f"),
                            Quantity = 1,
                            UnitPrice = 1.9f,
                            WholesalerId = new Guid("7ec52a66-5ce1-41ea-804c-2912873131fe")
                        });
                });

            modelBuilder.Entity("Domain.Entities.BreweryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brewery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d985e71e-7b84-48af-8b32-fd87148d9c71"),
                            Name = "William Brew"
                        },
                        new
                        {
                            Id = new Guid("25c74345-961b-49ac-9d2f-ed94123b3cc8"),
                            Name = "Genesis Brew"
                        },
                        new
                        {
                            Id = new Guid("5fafa7da-1759-424d-a78f-ef81fe6479f8"),
                            Name = "Supreme Brew"
                        },
                        new
                        {
                            Id = new Guid("cdb9fe2e-cda2-4c91-9a1b-35da889a9bed"),
                            Name = "Baguette Brew"
                        },
                        new
                        {
                            Id = new Guid("426b9381-8de1-4b49-a600-035a99617984"),
                            Name = "Zuzu Pils"
                        });
                });

            modelBuilder.Entity("Domain.Entities.WholesalerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wholesaler");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb891f07-af99-4f36-a2d4-0065cd8a1989"),
                            Name = "Genesis Shop"
                        },
                        new
                        {
                            Id = new Guid("7ec52a66-5ce1-41ea-804c-2912873131fe"),
                            Name = "Zuzu Shop"
                        },
                        new
                        {
                            Id = new Guid("68e33f1d-fefa-40f6-a117-5e601bd8a354"),
                            Name = "Pizza Beer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.BeerEntity", b =>
                {
                    b.HasOne("Domain.Entities.BreweryEntity", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.BeerStockItemEntity", b =>
                {
                    b.HasOne("Domain.Entities.BeerEntity", "Beer")
                        .WithMany()
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.WholesalerEntity", "Wholesaler")
                        .WithMany()
                        .HasForeignKey("WholesalerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
